### ISSUE TITLE
ERROR RSC-005 thrown on role="doc-epigraph"

### ISSUE THREAD

**Issue by atroia** [w3c/epubcheck#1019]
Used _role="doc-epigraph"_ in a section tag and I'm getting **ERROR RSC-005 : Error while parsing file: value of attribute "role" is invalid; **. I'm not seeing that this ARIA role has been deprecated or done away with.

**Comment by atroia** [comment]
_role="doc-cover"_ also throwing the same error.

**Comment by rdeltour** [comment]
`doc-epigraph` seems to be an omission on the roles allowed in `section` as defined in [ARIA in HTML](https://www.w3.org/TR/html-aria/#section), wdyt @mattgarrish? If yes we should file an issue there.

`doc-cover` is an image role and MUST NOT be set to a `section`, so that’s a legit error.

For reference: the rules of where DPUB ARIA roles are allowed in HTML are defined in the [ARIA in HTML](https://www.w3.org/TR/html-aria/) specification.

**Comment by TzviyaSiegman** [comment]
Good catch @rdeltour. @mattgarrish will you please log an issue on ARIA in HTML and the validator?

**Comment by mattgarrish** [comment]
Only roles that have inherit from the abstract `landmark` role are allowed on `section`, so the error is correct (see the superclass roles in the DPUB-ARIA definition tables).

`doc-epigraph` inherits from the abstract `section` role, so it falls into the document structure category. It can be used on `blockquote`, `div`, etc.

(The `section` superclass is not the same as the `section` element, in one of ARIA's odder quirks.)

**Comment by rdeltour** [comment]
> Only roles that have inherit from the abstract `landmark` role are allowed on `section`

Then there are inconsistencies in ARIA in HTML: e.g. `doc-abstract`, `doc-example`, `doc-qna`, and others inherit from the `"section"` role and are allowed on the `section` element…

**Comment by rdeltour** [comment]
> Only roles that have inherit from the abstract `landmark` role are allowed on `section`

I'm not sure I understand why that should be the case however. Why the `section` element would be limited to `landmark`-inheriting roles? This isn't the case for other non-DPUB ARIA roles (see `alert` for instance).

**Comment by rdeltour** [comment]
btw @atroia, while we're discussing all this (😊), you can always use the role `doc-epigraph` on the `blockquote` element, which likely makes the most sense in any case.

**Comment by mattgarrish** [comment]
> Why the `section` element would be limited to `landmark`-inheriting roles?

When we created the vocabulary, we were advised to assign landmark roles to the major sectional semantics and assign section to items that are not. That's why you won't find any mixing of `section` with the non-landmark roles in the examples.

I'm not sure why the ARIA document has mixed them, but we also weren't asked about the mapping in that document (that I remember). Definitely something we should clear up, as there may be assumed conditions on the use of the non-landmark roles (like no headings).

**Comment by atroia** [comment]
@rdeltour Thank you! That actually works out perfect, since I have an opening `blockquote` tag right below the `section` tag that I thought I needed. I also had no idea about the section superclass vs element, I still have so much to learn about ARIA.

**Comment by LaZay** [comment]
In HTML, a `section `can be recursively nested into a `section`. It is not possible to postulate that a `section `is ALWAYS used as a landmark. The parallel between `section ` and TOC  was just the most powerful and pedagogical example to show the interest of new HTML5 sections. It was not a requirement though. HTML5 has never put such a semantic constraint on `section` element definition.
https://www.w3.org/TR/2011/WD-html5-20110525/sections.html#the-section-element

**Comment by flittle8** [comment]
Hi, wondering if you can confirm if it's legitimate to add epigraph semantics to the section tag as per the [DAISY knowledge base](http://kb.daisy.org/publishing/docs/html/dpub-aria/doc-epigraph.html)?

**Comment by mattgarrish** [comment]
Yes, it is allowed on `section`.

The [ARIA in HTML](https://www.w3.org/TR/html-aria/#el-section) document is the authoritative reference for which roles are allowed on which elements. We've worked out the discrepancies that used to exist.
