### ISSUE TITLE
Fault on dl[role="doc-glossary"]

### ISSUE THREAD

**Issue by francofaa** [w3c/epubcheck#1029]
`<dl epub:type="glossary" role="doc-glossary" class="glossary">` faults on EPUBcheck 4.2-rc

https://www.w3.org/TR/dpub-aria-1.0/#doc-glossary indicates doc-glossary as a valid role for element dl

Error reads as follows: 
> Error while parsing file: value of attribute "role" is invalid; must be equal to "group", "list", "none" or "presentation"

**Comment by rdeltour** [comment]
@francofaa the rules for `doc-glossary` are a bit of a moving target. See w3c/html-aria#128.

@mattgarrish If I understand correctly, `doc-glossary` being a landmark it should be allowed on `section` elements (w3c/html-aria#128). However, does it also mean it should **not** be allowed on `dl` elements? If yes validator/validator#771 should also remove it on `dl`?

What rule should we implement in 4.2.0?

**Comment by rdeltour** [comment]
@francofaa see also the [fixed `doc-glossary` example in the DPUB-ARIA 1.1 draft](https://w3c.github.io/dpub-aria/#doc-glossary)

**Comment by mattgarrish** [comment]
> If yes [validator/validator#771](https://github.com/validator/validator/pull/771) should also remove it on `dl`?

The validator doesn't allow it on either `dl` or `section`, so the question is whether we should allow it on `dl`, too.

To date we've said no, because there was an issue about whether the implied role for `dl` was list, in which case having a landmark and `dt` and `dd` map to `term` and `definition`, respectively, would make a mess.

Looking again at ARIA 1.1, though, it has set the implied semantics for `dt` and `dd` to those roles, and the ARIA in HTML document now says that `dl` doesn't have an implied role. Which means we can reconsider whether to allow `dl` to also be a glossary.

**Comment by rdeltour** [comment]
> The validator doesn't allow it on either `dl` or `section`

Oh right.

> Which means we can reconsider whether to allow `dl` to also be a glossary.

Yeah, as far as I understand the all latest spec drafts (HTML, ARIA in HTML, AAM) are now aligned on the implied roles for `dl`/`dt`/`dd`, and it would make sense to allow `doc-glossary` there too.
But then, why not allowing other landmarks like `doc-credits`, `doc-endnotes`, `doc-qna`, etc… 🤯

For now, I'll leave this issue open as `status: blocked`, and we can fix the implementation when the spec landscape is clearer. As long as we allow `doc-glossary` on `section` elements, we have a reasonable workaround to recommend.

**Comment by mattgarrish** [comment]
> But then, why not allowing other landmarks like `doc-credits`, `doc-endnotes`, `doc-qna`, etc… 🤯

doc-qna had the same problem as doc-glossary: if dl is a list then you can't represent questions and answers as anything _but_ a list.

I'm not sure I follow how a definition list would define credits or endnotes or any of the other semantics we define, though. The idea isn't to allow semantics everywhere. There still has to be a term/definition relationship amongst the children of the element.

**Comment by rdeltour** [comment]
> I'm not sure I follow how a definition list would define credits or endnotes or any of the other semantics we define, though.

The native semantics of `dl` is pretty open in HTML, as it represents " an association list consisting of zero or more name-value groups (a description list)".

In fact they have an example that very much looks like credits:

```html
<dl>
 <dt> Authors
 <dd> John
 <dd> Luke
 <dt> Editor
 <dd> Frank
</dl>
```

Essentially, all the roles we define as "a collection" or "a series" of something would make sense on `dl`, no?

**Comment by mattgarrish** [comment]
Except that that's not how credit is defined:

>An acknowledgment of the source of integrated content from third-party sources, such as photos.

Credits in publications are generally either embedded in photographs or a bullet list section at the end of the work.

Just because something _can_ be expressed as a list, doesn't make it a good candidate for `dl`. We should be able to cite real patterns of use, and for credits and endnotes it seems more like theory.

**Comment by rdeltour** [comment]
I had a fresh look at the specifications and EPUBCheck's latest builds. All are on the same page. The `doc-glossary` role is allowed on `section` elements (and others elements accepting any roles, like `div`), but **not** on `dl` elements.

Closing this as "not an issue".
