### ISSUE TITLE
invalid URI reported twice

### ISSUE THREAD

**Issue by tofi86** [w3c/epubcheck#1033]
The URI `https://www.proasyl.de/thema/rassismus/fakten-gegen-vorurteile/##4%20` is a working URL in the respective website. However, Java doesn't parse it as a valid URI.

a) is this correct?
b) why is it reported twice? First as RSC-005 than as RSC-020?

Context: XHTML document, `<p class="test">text <a class="external" href="https://www.proasyl.de/thema/rassismus/fakten-gegen-vorurteile/##4%20">linktext</a></p>`

Browsers treat it as a working fragment id, although I see the issue with the website's sources and the fragment identifier. But it's hard to tell EPUB users to manually twaek working URL's just for EPUB.

**Comment by rdeltour** [comment]
> a) is this correct?

yes, character `#` is illegal in the fragment part of the URL, see the [_fragment state_](https://url.spec.whatwg.org/#fragment-state) section of the URL parsing algorithm, or the definition in [RFC3986](https://tools.ietf.org/html/rfc3986).

> b) why is it reported twice? First as RSC-005 than as RSC-020?

Not sure why; I need to create a repro to further test this.

Note that W3C's HTML validator service reports this as an error as well:

>> **Error**: Bad value `https://www.proasyl.de/thema/rassismus/fakten-gegen-vorurteile/##4%20` for attribute `href` on element `a`: Illegal character in fragment: `#` is not allowed.

**Comment by mattgarrish** [comment]
> see the fragment state section of the URL parsing algorithm

Browsers are using the URL Standard, no? I haven't tried to dig through it for this case, but there are rules for normalizing otherwise bad user URLs into something sensible. I suspect that's what's happening here, especially since HTML ids are so loose in what they accept now.

It should be escaped as `#%234%20`, though.

**Comment by rdeltour** [comment]
> Browsers are using the URL Standard, no?

Yes, that's where the URL parsing algorithm that I mentioned is defined. And yes, validation errors are not fatal; here's [what the URL Standard says about _validation errors_](https://url.spec.whatwg.org/#validation-error)

> A **validation error** indicates a mismatch between input and valid input. User agents, especially conformance checkers, are encouraged to report them somewhere.
>>Note: A **validation error** does not mean that the parser terminates. Termination of a parser is always stated explicitly, e.g., through a return statement.
>>
>>It is useful to signal validation errors as error-handling can be non-intuitive, legacy user agents might not implement correct error-handling, and the intent of what is written might be unclear to other developers.

**Comment by mattgarrish** [comment]
> that I mentioned

Heh, I only saw the RFC reference at the end. I shouldn't multitask.

**Comment by rdeltour** [comment]
> why is it reported twice? First as RSC-005 than as RSC-020?

So I had a deeper look:

- `RSC-005` is reported by the schema validation, since the datatype of the `href` attribute is set to `xsd:anyURI`.
- `RSC-020` is reported when we try to parse the URI in Java.

Given that there cases where these two errors are not redundant, and this is subject to change if we fully adopt the Nu Html Checker, I'd be tempted to not do anything here.

@tofi86 does it sound OK to you?

**Comment by tofi86** [comment]
> @tofi86 does it sound OK to you?

👍 

> It should be escaped as `#%234%20`, though.

yep, that's what I did to fix the issue with our customer.
