### ISSUE TITLE
generates ‘java.lang.StackOverflowError’ in both 

### ISSUE THREAD

**Issue by shashikumar1** [w3c/epubcheck#1044]
While we are working with 2GB RAM getting below error, However after adding -Xss512k before jar problem has been resolved but this has to handle.

generates ‘java.lang.StackOverflowError’ in both 

java -Xss512k -jar

**Comment by rdeltour** [comment]
I'm not sure I understand, can you please help me clarify the issue?

You said:
>  after adding -Xss512k before jar problem has been resolved 

which sounds like you could work around the StackOverflowError, like is advised in the [troubleshooting section of the doc](https://github.com/w3c/epubcheck/wiki/Running#troubleshooting). Correct?

> generates ‘java.lang.StackOverflowError’ in both

in both what? What is the exact problem and what do you expect EPUBCheck to do or behave differently?

**Comment by shashikumar1** [comment]
Basically I am asking for below issue that we know and earlier we are not receiving this error but now where 2GB ram available it will show an error message. Can this we can't fix in code as many people don't know about this issue and they are facing more problem to identify the java stack error so we request to handle this issue through code and user doesn't have to do anything.

Hope you understand based on below issues. 

java.lang.StackOverflowError
If EPUBCheck crashes with a StackOverflowError, try adjusting the thread stack size of your Java Virtual Machine. With most Java distributions, this can be done by using the -Xss option of the java command, like in the following example:

java -Xss512k -jar epubcheck.jar moby-dick.epub

**Comment by rdeltour** [comment]
> earlier we are not receiving this error but now where 2GB ram available it will show an error message.

Indeed, the schema were significantly updated in v4.2.0, and the new schemas are more demanding in memory. It is unfortunately a limitation we can't work around.

> we request to handle this issue through code and user doesn't have to do anything.

Setting the stack size cannot be done through Java code, since it has to be done at **before** launching the JVM.

If you need an easier way to distribute EPUBCheck to people, you can always provide a launcher script to your users, which would launch EPUBCheck with the `-Xss512k` option by default.

**Comment by shashikumar1** [comment]
If we provide launcher script with -Xss512k default then the system where this exception not available overthere it gives an error message like I have 8 GB Ram i10 system with windows 10. Whenever I run this it works fine but while sharing with other they faced issue of java stack overflow. Now in the process we are using single script to run ePubchecker across the organization so here we need to put some time of code that works on both environment or we have an identification way to identify this error based on some prerequistes. Please suggest. I have increased this on 1024k and now on all the system where error comes and where not comes are now working fine but it kills more time to find out a way here. That's why we are asking a permanent solution for this.

**Comment by laudrain** [comment]
@shashikumar1 hi, it looks to be an execution environment issue.
This is already documented in EPUBCheck wiki at:
https://github.com/w3c/epubcheck/wiki/Running#troubleshooting
As you say, when increasing Xss to 1024, it works fine, so it is not an EPUBCheck issue.

**Comment by shashikumar1** [comment]
Yes, I understand this but i want here to handle this in backend and why user will wait for this exception and then run this tag. We need to think for permanent solution and that is why I am asking if we can handle this in epubchecker if not, there are no issue.

**Comment by rdeltour** [comment]
Unfortunately, unless we start distributing a launcher script for EPUBCheck, there's nothing we can do on our side.

As you mentioned, the issue will not appear consistently everywhere. It essentially depends on the JVM and OS which is used to run EPUBCheck, which do not all have the same thread stack default size. That's one of the reasons why we do not want to provide a default launcher script in EPUBCheck; for many users, they won't even face the issue as their JVM will have a better stack size default.

In any case, since you apparently want to use a single script across your organization, it seems that you can solve this issue once and for all. If a size of 1024k works for you, then problem solved?

**Comment by rdeltour** [comment]
I'm closing this issue as invalid (out of scope given that we don't provide a launcher script), but feel free to keep commenting here!

**Comment by sthompson-celerity** [comment]
I know this is closed, but for future googlers like me, Downloading the base 64 version of java fixed this for me as well...
