### ISSUE TITLE
epub:type="endnote" - POP-UP not working in Ipad

### ISSUE THREAD

**Issue by Mustaf2659** [w3c/epubcheck#1057]
Hi,

While checking new epub:type="endnotes" and epub:type="endnote" for epub3, the pop-up was not working in the ipad device. But popup shown in the iBooks

**noteref:**
<sup><a  role="doc-noteref" epub:type="noteref" id="notes-ch1_1" href="notes-ch1.xhtml#notes-ch1-1">1</a></sup>

**Notes**
<section epub:type="endnotes" role="doc-endnotes">
<li id="notes-ch1-1" epub:type="endnote" role="doc-endnote" value="-0"><p><span class="en_tx"><a href="chapter1.xhtml#notes-ch1_1">1.</a></span>First Footnote</p></li>
</section>

But it's works fine when we use (rearnotes, rearnote) instead of (endnotes, endnote).

Provide your suggestion on this.

**Comment by Mustaf2659** [comment]
Hi,

While checking new epub:type="endnotes" and epub:type="endnote" for epub3, the pop-up was not working in the ipad device. But popup shown in the iBooks

**noteref:**

> &lt;sup&gt;&lt;a role="doc-noteref" epub:type="noteref" id="notes-ch1_1" href="notes-ch1.xhtml#notes-ch1-1"&gt;1&lt;/a&gt;&lt;/sup&gt;

**Note File**

> &lt;section epub:type="endnotes" role="doc-endnotes"&gt;
> &lt;li id="notes-ch1-1" epub:type="endnote" role="doc-endnote"&gt;&lt;p&gt;&lt;a href="chapter1.xhtml#notes-ch1_1"&gt;1.&lt;/a&gt;&lt;/span&gt;&#x2005;&#x2005;First Footnote&lt;/p&gt;&lt;/li&gt;
> &lt;/section&gt;

But it's works fine when we use (rearnotes, rearnote) instead of (endnotes, endnote).

Provide your suggestion on this.

**Comment by JayPanoz** [comment]
Not an epubcheck issue but a Reading App issue so you should open a bug report @ http://feedbackassistant.apple.com as I can remember this being clearly a discrepancy between iOS and MacOS – this is not the only one for those popups. With a bit of luck, others will have reported this bug, and it will escalate in their internal system if they are starting to see duplicate bug reports.

Until Apple fixes this issue, all you can do is using the deprecated `rearnote` if you absolutely want those popups so that’s no viable/long term solution.

**Comment by rdeltour** [comment]
@JayPanoz said it all.
Closing the issue as `invalid`.
