### ISSUE TITLE
Fragment identifier is not defined.

### ISSUE THREAD

**Issue by Bala6644** [w3c/epubcheck#1073]
The latest version of epub checker 4.2.2 is not reporting the fragment identifier error for the below issue.  However it's works validating using EPUB version 3.0.1 rules.

Identifier value is not mentioned in the &lt;a href=""&gt;.
Chapter 6 XHTML:
&lt;p&gt;There are present and &lt;a href="Chapter_9.xhtml#"&gt;Section 9.4&lt;/a&gt; .....&lt;/p&gt;

Chapter 9 XHTML:
&lt;h2 class="h3" id="head9-4"&gt;9.4 Meteor Data ....&lt;/h2&gt;

Thanks

**Comment by rdeltour** [comment]
thanks @Bala6644 and welcome 😊

I don’t thing there is any issue here however: `Chapter_9.xhtml#` is a valid URL to use in a `href` attribute, which is why EPUBCheck does not report any error here.

EPUBCheck does not check the link text ("Section 9.4") nor does it perform language processing to understand that the link should instead point to the related section’s specific ID. That would be a very complex thing to do in the general case. 

What EPUBCheck does is:
- check that the URL in the `href` attribute is syntactically valid (in your case, it is).
- check that any fragment specified in the URL (if any) actually exist (in your case, the fragment is empty so this check is irrelevant).

**Comment by rdeltour** [comment]
I’m closing the issue as `invalid` since EPUBCheck’s behavior is apparently correct here. However, please feel free to keep on commenting or reopen if you disagree (in which case, a sample EPUB would help us to further identify the situation 😊).

**Comment by Bala6644** [comment]
The EPUB checker 3.0.1 reported as an error.  The specified value "Chapter_9.xhtml#" is not pointed to the related section.

**Comment by rdeltour** [comment]
Can you please provide an EPUB to help us reproduce the issue?

**Comment by Bala6644** [comment]
I will send it you soon.

**Comment by Bala6644** [comment]
Unable to attach the epub file.

**Comment by rdeltour** [comment]
> Unable to attach the epub file.

you can send it to me by email at rdeltour @ gmail . com, or vie a sending service like [Firefox Send](https://send.firefox.com).

**Comment by Bala6644** [comment]
https://send.firefox.com/download/30b5c97c2452fbcd/#SuF1BKj7JZriBclY8wzrDQ

**Comment by rdeltour** [comment]
Thanks for the file! I could reproduce that `RSC-012` is reported in EPUBCheck v4.1.1, and is reported as error-free in EPUBCheck v4.2.1 (the latest stable version).

After having looked at the file, I confirm that the latest version is the correct one: there is no violation to the EPUB spec, so it is correct to not report anything. In other words, the previous behavior was a bug (empty fragments strings were rejected when they should have been allowed), which has since been fixed.

The spec basically says that a relative link must resolve to a location in the book, which it does in your case. That the location isn’t consistent with the link text is more of a QA issue, and again this would be very complex to check automatically in the general case.

**Comment by Bala6644** [comment]
Is it possible to validate the same EPUB with lower version 3.0.2

**Comment by Bala6644** [comment]
Sorry please validate with 4.0.2

**Comment by Bala6644** [comment]
Thanks for your Support.

**Comment by rdeltour** [comment]
> Is it possible to validate the same EPUB with lower version

Not really. EPUBCheck does not differentiate between EPUB 3 versions. The latest EPUBCheck (currently version 4.2.1) will always check the latest EPUB 3 version (currently EPUB 3.2). If you really want or need to check conformance to earlier outdated EPUB versions, you can always use older EPUBCheck versions (available on the [release pages](https://github.com/w3c/epubcheck/releases)).

**Comment by Bala6644** [comment]
Sounds good.
