### ISSUE TITLE
Remote Resource Error

### ISSUE THREAD

**Issue by Bala6644** [w3c/epubcheck#1074]
Getting remote resource error even if I specified the required properties in the OPF file.

<div class="frame1 mar-top1">
<iframe style="overflow:hidden; width: 100% !important; height: 690px !important;" class="frame1" src="https://oup-arc.com/ebook/access/content/fuller-intro-cj-brief-instructor-resources/cnn-video-criminal-law-blue-laws?options=name"></iframe>
</div>

<item properties="remote-resources scripted" id="html-chapter03" href="chapter03.xhtml" media-type="application/xhtml+xml" />

ERROR(RSC-006): E:/Bala/Projects/02-Books-IND/04_ePUB3/ePUB-Checker/sample.epub/OEBPS/chapter03.xhtml(150,235): Remote resource reference not allowed; resource must be placed in the OCF.
WARNING(OPF-018): E:/Bala/Projects/02-Books-IND/04_ePUB3/ePUB-Checker/sample.epub/OEBPS/chapter03.xhtml(149,149): The 'remote-resources' property was declared in the Package Document, but no reference to remote resources has been found.

Thanks

**Comment by rdeltour** [comment]
The EPUB spec does not allow iframes to point to remote resources (see the section on [Resources Locations](https://www.w3.org/publishing/epub32/epub-spec.html#sec-resource-locations)), which is why you get error `RSC-006`.

The other warning `OPF-018` is an implementation side-effect (if I remember correctly); the remote reference from the `iframe` being disallowed, it is not registered by EPUBCheck which then complains when checking the `remote-resources` property that no remote resource was actually found. In other words, you can safely ignore this warning when `RSC-006` was raised previously.

**Comment by rdeltour** [comment]
I’m closing the issue as invalid since EPUBCheck’s behavior is apparently correct here. However, please feel free to keep on commenting or reopen if you disagree!

**Comment by Bala6644** [comment]
Sound Good!!! Thank you.
