### ISSUE TITLE
Report non-conforming features with usage messages?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1106]
I came across the use of `typemustmatch` in one of the test files, but it's one of those existed-in-W3C-not-in-WHATWG items.

According to the now-standard spec, authors [must not use these features](https://html.spec.whatwg.org/multipage/obsolete.html#obsolete), but I know that advice will never completely fly because we've allowed things like border on table too long.

Should we be testing anything in the list, though, and/or should we consider issuing usage statements if encountered?

**Comment by mattgarrish** [comment]
Near the end of the test file errors are thrown for some of the features (contextmenu, dropzone, keygen, menus, pubdate, seamless). More reason to standardize an approach.

**Comment by rdeltour** [comment]
Adding to v5.0.0-rc, tentatively, to see if we can figure out an approach.

**Comment by rdeltour** [comment]
`typemustmatch` was removed from the schema following an HTML schema update in 22fa3b11, and we have a test that `RSC-005` is reported if the attribute is used.

I think the best approach is to keep on updating the HTML schemas as frequently as possible 😊.

I'm closing as `wontfix`, since the specific issue is handled, and we're relying on the validator.nu schemas for keeping up-to-date on the list of non-conforming features.
