### ISSUE TITLE
Help please :(

### ISSUE THREAD

**Issue by yaninitayan** [w3c/epubcheck#1281]
Hi! I'm new here. I have problems with my ePub. Can anybody help me to solve them?
Sigil check says that everything is OK.
But then uploading the ePub to a web appear a advertise: MySQL query eeror:: Error en: SELECT autor_foto FROM autores WHERE id= LIMIT 1

<html><body>

ERROR | OEBPS/Text/indice.xhtml | 112 | 91 | Fragment identifier is not defined.
-- | -- | -- | -- | --
WARNING | ./tmp/uploads/1632233950855_0000002909/inputFile/Introduccion_Innovacion_Sistematica_(03-09-21).epub | - | - | Item 'OEBPS/Fonts/Montserrat-Bold.otf' exists in the EPUB, but is not declared in the OPF manifest.
WARNING | ./tmp/uploads/1632233950855_0000002909/inputFile/Introduccion_Innovacion_Sistematica_(03-09-21).epub | - | - | Item 'OEBPS/Fonts/Montserrat-BoldItalic.otf' exists in the EPUB, but is not declared in the OPF manifest.
WARNING | ./tmp/uploads/1632233950855_0000002909/inputFile/Introduccion_Innovacion_Sistematica_(03-09-21).epub | - | - | Item 'OEBPS/Fonts/Montserrat-Italic.otf' exists in the EPUB, but is not declared in the OPF manifest.
WARNING | ./tmp/uploads/1632233950855_0000002909/inputFile/Introduccion_Innovacion_Sistematica_(03-09-21).epub | - | - | Item 'OEBPS/Fonts/Montserrat-Regular.otf' exists in the EPUB, but is not declared in the OPF manifest.

</body>
</html>

**Comment by MyDK** [comment]
Hi :)
Not sure where you are uploading your file to? - but EPUB files must always be checked with EPUBCheck. EPUBCheck exists as a plug-in to Sigil, you can find a link to it, here from EPUBChecks' official site:

https://www.w3.org/publishing/epubcheck/docs/apps-and-tools/#epub-editors

The messages are about the fonts in your file cannot be found in the OPF manifest. Fonts are not properly declared. 

- so maybe you are trying to open your file in an environment that doesn't support EPUB? Or doesn't support those fonts 🤔
I think we need to know what you are trying to do, in order to guide you to a solution.

**Comment by yaninitayan** [comment]
Hi! 
I solved it! 
I uploaded the fonts in the fonts folder and the error "OEBPS / Text / index.xhtml" was simply a duplicate path in the index.
