### ISSUE TITLE
EPUB Spacing issue

### ISSUE THREAD

**Issue by atmosproductions** [w3c/epubcheck#1487]
Hi

I have a valid epub file now which looks great on Apple Books but when I test the same file on kindle. The spacing between the paragraphs is condensed loads. Is there a way to make the spacing the same across all platforms as a default/minimum setting before any user preferences are changed?

I have attached two images to show what I mean. When I export the project with double spacing, it looks how it should in kindle which is really odd.

I’d rather distribute one epub file for all platforms rather than upload a different one for kindle.

**Comment by atmosproductions** [comment]
![Uploading D1270DAC-3552-4890-8DD3-D9B7C7F53212.jpeg…]()

**Comment by atmosproductions** [comment]
![F9EC6CA3-A337-4EA5-A00C-619A93A32960](https://user-images.githubusercontent.com/126411550/222783435-06bba075-e5df-4cd3-8588-2a8195f3347d.jpeg)
![DAC64A65-D3D7-4143-8ABA-D216E360DFC4](https://user-images.githubusercontent.com/126411550/222783440-82853f74-7768-4ee7-9563-5793bf49b697.jpeg)

**Comment by Doktorchen** [comment]
1. Seems to be not related to epubcheck.

2.1. If you consider the appearence/presentation of the poem (?) only decorative, you can use a CSS stylesheet to recommend a specific presentations to user-agents.

2.2. If you assume, that graphical appearence/presentation is relevant, use SVG instead of XHTML+CSS. With SVG you can define the position of each glyph precisely - well, better to add a font-file to get really almost the same appearance in each viewer.

Remaining problem: Some programs (for example calibre >=4) have (different) bugs, causing even worse problems with advanced EPUBs for the audience.

**Comment by rdeltour** [comment]
I'm closing this issue as this is not related to EPUBCheck. 

Unfortunately I appreciate that there is no single central forum for these kind of discussions. You may try to reach out to the EPUB community via other channels like StackOVerflow or Twitter (#eprdctn hashtag).

But this issue tracker should only be used to report bugs or feature requests with EPUBCheck 😊.
