### ISSUE TITLE
EPUB checker option "--version" issue

### ISSUE THREAD

**Issue by Bala6644** [w3c/epubcheck#1533]
@rdeltour 
The EPUB validation has failed while using the option "--version" in the command line argument and getting the default message in the log file if there are any errors or warnings in the source EPUB file. The previous version 5.0.1 correctly indicated the error/warning with version details. Kindly check and assist us to resolve this issue.
 
EPUBCheck v5.1.0
Messages: 0 fatals / 0 errors / 0 warnings / 0 infos / 0 usages

EPUBCheck completed

Usage
C:\Users\euser>java -jar -Xss1024k "C:\Localfiles\Support\ePUB-Checker\5.1.0\epubcheck.jar" "C:\Localfiles\Support\ePUB-Checker\test.epub" --version > "C:\Localfiles\Support\ePUB-Checker\test.log" 2>&1

[test_5.0.1.log](https://github.com/w3c/epubcheck/files/12023958/test_5.0.1.log)
[test_5.1.0.log](https://github.com/w3c/epubcheck/files/12023959/test_5.1.0.log)

**Comment by Bala6644** [comment]
Hi @rdeltour ,
Thanks for your kind support.

Yes, I need to print the  EPUBCheck version number and the check messages at the same time.

**Comment by TobiasWantzen** [comment]
I'm in need of outputting the version info with the check messages either, but would propose to introduce a new CLI option for this, maybe "-i"/"--info", which will simply add the version to the "normal" output, e.g.:
```
java -jar /Applications/twa-eBook-Produktion/epubcheck/epubcheck.jar -i xyz.epub
```
will then output:
```
EPUBCheck v5.1.0 abgeschlossen
Verwendung der EPUB 3.3 Prüfungen
ERROR(RSC-005): xyz.epub/OEBPS/content.opf(3,56): Validierungsfehler: package dcterms:modified meta element must occur exactly once

EPUBCheck mit Fehlern abgeschlossen
Meldungen: 0 Schwerwiegende Fehler / 1 Fehler / 0 Warnungen / 0 Informationen
```
\
To "--version":
```
java -jar /Applications/twa-eBook-Produktion/epubcheck/epubcheck.jar --version
```
now outputs this:
```
EPUBCheck v5.1.0
Meldungen: 0 Schwerwiegende Fehler / 0 Fehler / 0 Warnungen / 0 Informationen
```
This is very misleading. Please reduce the output to the version info only and then exit:
```
EPUBCheck v5.1.0
```
Misleading, because in my workflow, which runs for a decade now, "--version" was always part of the CLI command to test my epubs, so it took me some time to realize that there were errors in the epub I was checking, even though epubcheck says there were none.

**Comment by TobiasWantzen** [comment]
I made some testing and
```
java -jar /epubcheck.jar --help
```
outputs the trailing
```
Meldungen: 0 Schwerwiegende Fehler / 0 Fehler / 0 Warnungen / 0 Informationen

EPUBCheck abgeschlossen
```
either.
This should be fixed!

For a workaround until this is fixed:
```
java -jar /epubcheck.jar --version -q
java -jar /epubcheck.jar --help -q
```
suppresses the misleading check informations at the end.
