### ISSUE TITLE
Href to local image seems to cause issues on validation

### ISSUE THREAD

**Issue by user414** [w3c/epubcheck#1539]
A simple test file like this

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
    <title>Bug</title>
</head>

<body>
    		<h1>bug</h1>
            <figure>
                <img src="../Images/test.jpg"/>
                <figcaption><a href="../Images/test.jpg">Download</a></figcaption>
            </figure>

</body>
</html>
```

Causes a validation error with epubcheck v 5.1.0 like this

ERROR(RSC-010): ../untitled.epub/OEBPS/Text/test.html(13,75): Reference to non-standard resource type found.

**Comment by user414** [comment]
After further investigation it is the href to the local image that seems to cause an issue. I can't find seem to find that this is illegal in the specs, can someone confirm?

**Comment by mattgarrish** [comment]
> After further investigation it is the href to the local image that seems to cause an issue.

There are two reasons for this: 1) you can only hyperlink to a [foreign content document](https://www.w3.org/TR/epub-33/#dfn-foreign-content-document), like a jpeg, [if it is in the spine](https://www.w3.org/TR/epub-33/#spine-inclusion-req); 2) if you link to a foreign content document, you have to have a [manifest fallback](https://www.w3.org/TR/epub-33/#sec-manifest-fallbacks) to an epub content document.

Reading systems aren't going to let you download resources out of an epub, so putting a hyperlink to a local jpeg isn't going to have the intended affect. What they will do is try to open the jpeg as though it's another document in the publication.

We discussed downloading resources a couple of revisions back (e.g., using the `download` attribute to differentiate from resources that should open in the spine), but there wasn't enough interest to pursue it.

**Comment by user414** [comment]
@mattgarrish Thanks for your prompt response. After reading some of the links you provided they seem to only discuss foreign content there does not seem to be anything making linking to internal content like jpeg illegal, albeit perhaps without the intented behaviour. 

Just to provide some context, the use case is an automated epub generation from markdown content that is normally deployed on a web site. It was preferred to do the least custom handling of element as possible, and the reading systems opening the jpeg is reasonable even though it was not the original intent and was seen as preferable to a custom handling of those elements. 

If it is illegal in the Epub specs then there is no choice but if it is legal and it was a lack of interest, e.g. using the download attribute to differentiate as you mentioned maybe being a potential solution, then perhaps it might be more efficiency to implement that and do a pull request instead of a custom solution in the generator. It may be worth investigating further.

**Comment by mattgarrish** [comment]
Per the paragraph in the second link in my previous post:

> [EPUB creators](https://www.w3.org/TR/epub-33/#dfn-epub-creator) MUST list in the spine all EPUB and foreign content documents that are hyperlinked to from publication resources in the spine, where hyperlinking encompasses any linking mechanism that requires the user to navigate away from the current resource. Common hyperlinking mechanisms include the [href](https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-href) attribute of the [[html](https://www.w3.org/TR/epub-33/#bib-html)] [a](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) and [area](https://html.spec.whatwg.org/multipage/image-maps.html#the-area-element) elements and scripted links (e.g., using DOM Events and/or form elements).

You can't hyperlink to a jpeg without listing it in the spine, in other words. And per the other links, you can't have a jpeg listed in the spine without a manifest fallback to an xhtml or svg content document. That's why you're getting the error you're getting.

If you add a spine entry and include add a fallback to an xhtml or svg document, then you'll get past the error, but users still won't be able to download the jpeg, at least not on any reading system I can think of.

There are reading systems that let you tap on images to view them in expanded form without having to do anything special, so you might want to consider if a link is even necessary if it's only to view an enlarged image.

It is legal to add the `download` attribute, but no reading systems will do anything with it and it doesn't get you around the existing epub requirements. It would take changes to the specification to make it legal to omit a spine entry when the attribute is present, but that's probably not going to happen any time soon (EPUB 3.3 just came out and there are no plans at this time for another revision). If you think it's important to have downloads, though, feel free to open an issue in the [epub-specs repository](https://github.com/w3c/epub-specs) for the working group to consider. We can't solve that issue here.

**Comment by user414** [comment]
@mattgarrish Thanks for your detailed explanation, it's now clear. Closing as this is not a bug.

For information in case others stumble on this issue, in the end we will probably go the fallback route that get past the error but does nothing. It can be reused in the cases where href have the download attribute, anyway we need a fallback for remote resources. This will also allow future readers that may decide to implement a download feature to work out of the box versus a custom handling of elements that would completely remove or alter the content. Another consideration is our generation would skip putting that image in the epub if it was only referred in that 1 element. It would be completely gone thereby hindering future readers without rebuilding the epub file in the future. On a cursory reflection, the fallback that does nothing much seems preferable.
