### ISSUE TITLE
Error when adding language attribute in package element in EPUB 2

### ISSUE THREAD

**Issue by Changilainen** [w3c/epubcheck#1553]
For accessible ebooks there should be a language attribute (`xml:lang="en"`) added in the package element ([http://kb.daisy.org/publishing/docs/epub/language.html](http://kb.daisy.org/publishing/docs/epub/language.html)). At the end of the web page, it's mentioned that this applies to EPUB 2 and 3.

If my ebook is EPUB 3, I don't receive any errors with epubcheck 5.1.0 but if my ebook is EPUB 2, I receive the following error:
`Col: 102: ERROR(RSC-005): Error while parsing file: attribute "xml:lang" not allowed here; expected attribute "id"`

Is the problem in epubcheck or isn't the language attribute allowed here in EPUB 2 ebooks? I checked the [EPUB 2.0.1 specification ](https://idpf.org/epub/20/spec/OPF_2.0_latest.htm)but didn't find anything about the language attribute not being allowed in the package element.

**Comment by mattgarrish** [comment]
EPUB 2 does not allow xml:lang on the package element, which was a terrible choice in my opinion - and one we can't revisit anymore. You have to declare the language over and over on every metadata element that has text content. EPUB 3 fixed that by making xml:lang a global attribute (which arguably goes too far in the other direction since it can be specified where it has no value, like on manifest and spine items).

The knowledge base is primarily written for epub3 content. I'll go back and add a note about this particular quirk of epub 2. Thanks for pointing out that difference is missing from the page!
