### ISSUE TITLE
role="math" on images

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epubcheck#1562]
When following the WAI ARIA 1.2 example for using `role="math"` on an image element to indicate that it represents a mathematical expression (https://www.w3.org/TR/wai-aria-1.2/#example-8), EPUBCheck reports an ERROR RSC-005 stating that the value of the "role" attribute is invalid.

From the WAI ARIA 1.2 spec:

> While it is not ideal to use an image of a mathematical expression, there exists a significant amount of legacy content where images are used to represent mathematical expressions. Authors SHOULD ensure that images of math are labeled by text that describes the mathematical expression as it might be spoken.

However, EPUBCheck doesn't recognize `math` as a valid value for the `role` attribute, resulting in a false positive error.

Here you can find a sample EPUB file exhibiting this issue for testing purposes: [quadratic-formula.epub.zip](https://github.com/w3c/epubcheck/files/15401438/quadratic-formula.epub.zip)

**Comment by mattgarrish** [comment]
This doesn't look like a problem to fix in epubcheck. You've put the role on an `img` tag where it isn't valid per the [ARIA in HTML specification](https://www.w3.org/TR/html-aria/#el-img).

I think you need to take this to the ARIA group to sort out whether it is allowed on images or not and update the ARIA in HTML document accordingly. Validation of roles normally come from the validator.nu code, so that needs updating to fix the issue here, and they don't usually modify their code until the ARIA in HTML document is updated.

**Comment by mattgarrish** [comment]
> Sounds like there are some major confusion using role="math"

The ARIA spec appears to be the source of this markup (see the [section on polyfilling the equation](https://w3c.github.io/aria/#plain-html-or-polyfill-dom-result-of-the-mathml-quadratic-formula)). They show an example of transforming math to an image and the markup also shows the role on the `img` tag.

If I try it out in a browser and check the accessibility tree, the alt text is correctly associated with the role, so I suspect it's the ARIA in HTML doc that is out-of-date. But fixing it and then the validator is usually what's necessary to get a change into epubcheck.

**Comment by gregoriopellegrino** [comment]
Okay, so I'll open an issue for ARIA-HTML.

**Comment by rdeltour** [comment]
This was very recently updated in w3c/html-aria#525 and validator/validator#1773. I'll update the validator.nu schemas to bring the fix to EPUBCheck.
