### ISSUE TITLE
value of attribute "id" is invalid; must be an XML name without colons

### ISSUE THREAD

**Issue by rdeltour** [w3c/epubcheck#307]
_From [kbharath...@gmail.com](https://code.google.com/u/101707431231837135457/) on September 21, 2013 19:07:31_

PROBLEM: epub 2.0 validation error METHOD: What steps will reproduce the problem? 1. 2. 3. RESULT: What happens? EXPECTED: What did you expect to happen? It is very important to state what your expectation is. PLATFORM: What version of the product are you using? On what operating system? ADDITIONAL INFO: Please provide any additional information below.

**Attachment:** [mallora.epub](http://code.google.com/p/epubcheck/issues/detail?id=308)

_Original issue: http://code.google.com/p/epubcheck/issues/detail?id=308_

**Comment by pjkaufman** [comment]
I am not sure if this is something that would be accepted in epub check, but I think it would be helpful to mention that an epub's XML name cannot start with numbers unless that is not valid in XML already. This error had me questioning things for a while since there was no mention of numbers not being allowed at the start of the id and XML parsers I used did not error out on the syntax. So maybe they are just fault tolerant or maybe it is just a rule for epubs?

But either way, I think that updating the wording could help alleviate confusion with this.

If this is considered acceptable, I could take a stab at making the wording update.
