### ISSUE TITLE
hyperlink to non-standard resource of type 'image/png'

### ISSUE THREAD

**Issue by juh2** [w3c/epubcheck#324]
I am just a user of epubcheck with no knowledge about the specs, so this might be nonsense. I am not sure whether these error messages are intended.

I have some epubs which does not validate against epubcheck because they contain images. 

They are included like this:

```
<a class="reference internal image-reference" href="_images/sphinx-logo.png"><img alt="_images/sphinx-logo.png" src="_images/sphinx-logo.png" style="width: 160.0px;" /></a>
```

They are displayed fine. But epubcheck throws the error message
hyperlink to non-standard resource of type 'image/png'

**Comment by rdeltour** [comment]
My understanding is that it's perfectly valid to have hyperlinks pointing to images, so it sounds like a bug indeed.

The Content Documents spec does not say it is invalid in the [XHTML content conformance section](http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-conf-content) ; the Publications spec does mandate that references to EPUB Content Documents must be in the spine, but does not otherwise prevent references to other documents like images.

@mattgarrish can you please confirm? Is it a spec oversight or am I missing the obvious ? (I always thought the intent was to prevent a RS to open a non Content Doc directly, but this doesn't seem to be actually forbidden, except from the Nav Doc).

**Comment by mattgarrish** [comment]
Somewhat predates me, as even EPUB 2 is silent on this, but I would interpret the epubcheck error as correct.

I guess you could call it a spec ambiguity since we don't specifically address how hyperlinks open, but local resources are publication resources and you can't put an image in the spine, which is the context in which local resources render.

External references can simply be passed out to a browser to spawn, but I don't expect it would be quite so trivial for a local resource.

But feel free to open an issue for 3.1 if you want the WG to give a definitive answer. I think it would be good to have.

**Comment by rdeltour** [comment]
Thanks for the review :+1: 

I will create a spec issue ; in the mean time, and since we both feel this may well be a spec oversight, I won't revert EpubCheck's behavior just now (in case it does become a well-specified error in 3.1).

I'm keeping the issue open until this is solved at the spec level.

**Comment by rdeltour** [comment]
see idpf/epub-revision#572

**Comment by rdeltour** [comment]
Removing from the `4.0` milestone since this depends on spec clarification.

**Comment by mattgarrish** [comment]
Closing this issue as epubcheck is working as expected. If you hyperlink to a local image, it has to be listed in the spine and have a CMT fallback.
