### ISSUE TITLE
Check if the presence of a `title` child in an XHTML `head` element is required

### ISSUE THREAD

**Issue by rdeltour** [w3c/epubcheck#448]
Currently, this is naïvely checked and reported at the `USAGE`-level in `HTML_033`. However, [HTML5 says](http://www.w3.org/TR/html5/document-metadata.html#the-head-element) that the `title` element is not systematically required, e.g. when the HTML document is an `iframe` `srcdoc` document.

**Comment by mattgarrish** [comment]
The title can't be obtained from a higher-level protocol in EPUB, so that only leaves an exclusion for srcdoc. I tried validator.nu and the w3c validator and neither of them validated the contents of srcdoc.

**Comment by rdeltour** [comment]
Matt and I discussed this, and we don't think the publication title should be considered as an acceptable "higher protocol", since it's may not be available to the reading system. The reading system is left with no title and will fill in the file name as an alternative, which is why we push people to always specify titles for accessibility.

**Comment by rdeltour** [comment]
Resolution: allow missing `title` in the RNC schema, but report them as a `WARNING` using Schematron.

**Comment by rdeltour** [comment]
Done in #934, will be released in v4.2.0.

**Comment by elmimmo** [comment]
I do not agree that an XHTML document inside an EPUB can be considered atomic from a semantic point of view as, if I am not mistaken, nothing in the specs says they must or, even, how EPUB must be fragmented internally at all (i.e. one could split the text in two documents between two consecutive paragraphs just because). It cannot be said, therefore, IMHO, that XHTML `title` necessarily has any significance whatsoever. If anything, I think it is the current most lower chapter title wherever the document is inside the reading flow the most specific “topic” in that reading point that one could sensibly assume. Making sure each `title` contains that is maintenance burden, so preferably not, if unnecessary.

Of course, if reading systems do display the filename in the absence of `title`, that is just ugly… But is there any that does so, indeed?

If not, I would assume most of the times `title` is a just an inertial placeholder (or just there so epubcheck shuts up about it) and therefore cruft.

**Comment by mattgarrish** [comment]
> Of course, if reading systems do display the filename in the absence of `title`, that is just ugly…

One clear problem we've had with a lack of titles is in web-based reading systems. Because they use iframes for the content, the title is what is used to announce the purpose of the frame. Since there's no title attribute (or all a reading system could provide is some generic statement if it tried), you may get the file name read out in the absence of a title within the document that can be used.

That's why it's problematic to say that titles don't matter in EPUB. They exist to give context in situations like this. I don't know if any reading systems use them for bookmarking, but it's another instance where the title may be the only meaningful name to associate with the content (exactly because chunking may lead to weird heading-less documents).

But more specifically here, it's HTML that requires a title when there isn't a higher-level protocol that provides one. EPUB doesn't fully meet that requirement, as the publication title gives a context to the work as a whole but isn't always available or useful on a document-by-document basis. You really need both.
