### ISSUE TITLE
Adding optional check: "linearity" of SMIL file

### ISSUE THREAD

**Issue by pettarin** [w3c/epubcheck#494]
I think that adding an optional check on the "linearity" of a SMIL file might be useful to people editing their SMIL by hand.

By "linearity", I mean checking that `clipBegin` of (i+1)-th fragment equals `clipEnd` of i-th fragment (if they reference the same audio).

The rationale is that many "real world" (= excluding those in the EPUB test suite...) SMIL files satisfy this condition, and editing SMIL files by hand is really error-prone, due to the digits-nature of the clipBegin/clipEnd attributes.

I propose to add this as an optional check, e.g. to be required by specifying a switch (e.g., `--linear-mo`), possibly emitting a WARNING.

Currently, I perform this check using a custom Python script that I run in cascade, but I guess others might be interested in having such a check directly inside EpubCheck.

I can code it, but only if it is going to be merged. (Is there a policy somewhere defining what kind of new features EpubCheck should accept?) Otherwise, I will simply keep using my Python script for good.

Looking forward to hearing feedback.

**Comment by mgylling** [comment]
Hi Alberto,
A contribution of code to run this test would be most welcome. There are 
actually several tests in the MO area that could be added (e.g. that a 
clip time corresponds to a possible time in the audio, that opf time 
metadata is correct, etc). But we need to start somewhere, and this test 
is an as good start as any AFAICS.

One option could be to not use the commandline switch that you suggest, 
but instead to run this test unconditionally, and report any fails using 
the USAGE level in the Report (since this would not breach any RFC2119 
statement).

Thoughts?

/markus

**Comment by pettarin** [comment]
It sounds good.

**Comment by tofi86** [comment]
refs #726 #568

**Comment by rdeltour** [comment]
This was done in #1180, and now a usage in #1259. Closing.
