### ISSUE TITLE
note changes to Java licensing

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/epubcheck#866]
See https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html for summary

**Comment by tofi86** [comment]
We switched to testing with OpenJDK lately: https://github.com/w3c/epubcheck/blob/master/.travis.yml#L3
However, we still test with old Oracle JDK releases < version 11.

In the README file we recommend a Java Development Kit.

In the Wiki I added a change so to make clear to use Open JDK 11+:
* https://github.com/w3c/epubcheck/wiki/Running

Generally speaking I think we're on a safe side here as we're not using or relying on Oracle technology.

**Comment by danielweck** [comment]
So far I've "successfully" used Oracle JDK v11.0.1 from https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html to build and run EPUBCheck (I just get this error message https://github.com/w3c/epubcheck/issues/859 ).

I will also try OpenJDK v11.0.1 from https://jdk.java.net/11/

Side note (somewhat related): the other day I failed to launch the official DAISY Pipeline2 app using Java 11 (JDK runtime), because of missing libraries in the Java framework (`java.xml.bind` if I remember correctly) A bunch of EE libs which had been deprecated in Java 9 have now been removed, see https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html#JDK-8190378 Right now, EPUBCheck does not seem to be impacted by this breaking change in the Java runtime. Just in case, the workaround is to ship/install the missing libs using Maven or some other distribution mechanism. This is not developer/user-friendly though, so best to stay away from the said libs.

**Comment by rdeltour** [comment]
Closing this issue as `wontfix`. The continuous integration server runs EPUBCheck tests on various JVM versions, going back to OpenJDK 7; if users want to opt out of recent Oracle JVMs and their debatable licensing choices, they're welcome to do so 🙂.

If EPUBCheck fails on specific JVMs, we can open dedicated issue.
