### ISSUE TITLE
Allow the latest recommended SVG for content documents

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#893]
The Content Documents specification uses an auto-updating reference to the latest W3C version of SVG so that changes can be immediately reflected in validation. Currently this is SVG 2.

Note that part of this change is that the previous restrictions on the use of animation elements and events is removed.

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-overview-relations-svg

**Comment by rdeltour** [comment]
The schema update relies on the SVG schemas included in the Nu Html Checker, which is not strictly checking SVG 2, but adopts a more pragmatic approach ("There are otherwise no plans to add blanket support for SVG2 as a whole", see validator/validator#564).

I think we should follow the Nu Html Checker here (to the extent EPUBCheck can, i.e. currently limited to the schemas). This is what is done in #934.

**Comment by mattgarrish** [comment]
And as noted in https://github.com/w3c/publ-epub-revision/issues/1219 the reference is technically still 1.1. I wasn't looking closely at the status of the linked SVG document, which is still only a CR.

But in any case, I agree we should follow the model adapted by the nu checker.

**Comment by rdeltour** [comment]
OK, closing the issue for now. We can reopen ad hoc issues if user complain that valid SVG content is rejected by EPUBCheck.
