### ISSUE TITLE
The hasFeature version parameter is not allowed with epub-defined features

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#908]
Issue a warning if the version parameter is specified for any of the following:

- dom-manipulation
- layout-changes
- touch-events
- mouse-events
- keyboard-events
- spine-scripting

The version parameter is only defined for use querying proprietary features.

(Again, I don't know if this is verifiable, but adding for review.)

Reference: https://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#app-ers-hasFeature-desc

**Comment by rdeltour** [comment]
EPUBCheck currently cannot seriously check JS content. Some checks are done in the [EpubScriptCheck](https://github.com/w3c/epubcheck/blob/v4.2.0-alpha-1/src/main/java/com/adobe/epubcheck/ctc/EpubScriptCheck.java#L170) class, but these are based on regex parsing, which is shaky at best can even result in false negatives. I'd be wary of reporting anything other than `USAGE`-level stuff there.

These leaves us with two options:

a. implement the check with regex-parsing and report it as `USAGE`
b. consider it out of scope due to technical limitations, and close this issue as `wontfix`

I'm leaning towards option (b). Please upvote or comment if you disagree!
