### ISSUE TITLE
Report 3.x validation as following the EPUB 3.2 rules

### ISSUE THREAD

**Issue by rdeltour** [w3c/epubcheck#943]
It current says:

```
Validating using EPUB version 3.0.1 rules
```

Thanks for the catch @murata2makoto!

**Comment by murata2makoto** [comment]
Ishizu-san has an interesting suggestion.  He proposes that every added errors/warnings should be accompanied by the version number of the underlying EPUB specification.

Publishers often have to validate old publications using new epubcheck.  This is for example because new ebook stores require that every publication passes epubcheck.  Usually, such validation of past publications will lead to errors/warnings that were not issued before.  If every error/warning indicates the version number of the underlying EPUB specification, it will become easier to handle such newly issued errors/warnings.

**Comment by rdeltour** [comment]
> He proposes that every added error/warning should be accompanied by the version number of the underlying EPUB specification

The EPUB 3 CG decided in w3c/publ-cg#68 to **not** differentiate specification versions when checking EPUB 3.x publications. This question was asked specifically to avoid having to maintain a check-to-spec-version mapping (which would unfortunately not be as straightforward as it may seem) 😊
