### ISSUE TITLE
epubcheck 4.2.0.-beta: "display-seq" and WARNING

### ISSUE THREAD

**Issue by toshiakikoike** [w3c/epubcheck#990]
In EPUBCheck 4.2.0-beta, "display-seq" becomes a WARNING.
This may cause trouble in production or distribution scenes especially in Japan because
  1. most of the epub files created in Japan (which are 3.0.1) contain "display-seq"
  2. many publishers or distributors demand EPUB files with no errors and warnings

One idea I would like to propose to avoid this is 
to treat it (and other deprecated features) as USAGE INFORMATION message which is by default OFF.
Is that possible?

* This originally comes from the similar argument in @w3c/publ-epub-revision#1186
https://github.com/w3c/publ-epub-revision/issues/1186#issuecomment-439085684

**Comment by rdeltour** [comment]
Thanks for the report @toshiakikoike. 
I appreciate that reporting deprecation as `WARNING` will require production workflows to be adapted, as most distributors will reject EPUBs with any warning.

Currently the spec is clear that deprecated features are SHOULD NOT, so reported as WARNINGs in EPUBCheck. Changing that, or adding a new reporting level in EPUBCheck, would need to be agreed by the CG.

Could you open a new issue to the EPUB 3 CG instead? (not specifically about `display-seq`, but about any deprecated feature).

**Comment by mattgarrish** [comment]
It might be better just to ask for a reconsideration of `display-seq` being deprecated in the epub tracker. It can be overridden by the specification without deprecating it.

We discussed deprecation and warnings earlier on in this revision (and in 3.1). One point I remember being made is that if we can't issue a warning, then there's almost no point in deprecating anything. Few people even know how to get usage messages, let alone look at them. And if we can't deprecate things, the features are going to linger around causing confusion for authors.

**Comment by ShinyaTakami** [comment]
As Koike-san mentioned, we use "display-seq" for many of EPUB3 files in Japan.
And "WARNING" by epubcheck will prevent from delivering EPUB files at some major eBook stores.

Options below may be fine for us.
- Reconsideration of deprecating "display-seq" in EPUB3.2
- epubcheck will consider the target versions of EPUB3 (rejected at https://github.com/w3c/publ-cg/issues/68)
- epubcheck will report deprecated features in EPUB3.2 as NOT WARNING (proposed by Koike-san)

Anyway, we (publishers in Japan) don't have any intention to disturb improving epubcheck to adapt EPUB3.2 but we strongly hope that our EPUB3 files (already created and delivered in Japan) will not be marked as ERRORs or WARNINGs by future versions of epubcheck.

Otherwise, it will be difficult for us in Japan to use the new version of epubcheck (over 4.2.0) because it will take long time and need vast cost to modify existing EPUB files in Japan.

We appreciate that developers for epubcheck will recognize this WARNING issues as critical in Japan.

**Comment by Doktorchen** [comment]
I use "display-seq" in most books (typically for stores outside Japan).

Because it happened already before, that epubcheck versions in use by stores reported wrong warnings, a distributor was already informed, that a warning is not always related to a problem within a book, it can be as well a problem of the checker or the recommendation (as here: one version indication for different versions). This worked to get the distributor (and related shops) to ignore such warnings, because they did not want to check manually, whether the warning itself is a bug or that there really is a problem in the book ;o)

The simplest solution (as for several others backward incompatibilities) for EPUB 3.2 would be to spend a new version number. With this a program like epubcheck can distinguish between EPUB 3.0 books and EPUB 3.2 books, avoiding confusion.

Remains the problem, what to use instead of display-seq in EPUB 3.2 books.
If 3.2 does not provide this feature anymore, it is still possible to refer to an own vocabulary to indicate the order of metadata. Of course - as typically for the current display-seq - user-agents will not care about it, it is only to inform experts about the intended interpretation.

**Comment by clapierre** [comment]
One idea may be that any EPUB's marked as version 3.2 WILL report deprecated items as WARNINGS. but any older EPUB that has an earlier version such as 3.0.1 etc will not report them as warnings.  So  any future EPUB will need to remove that deprecated item or they will receive a WARNING upon checking but existing EPUBs will not be flagged as a WARNING.

**Comment by rdeltour** [comment]
@Doktorchen 
> The simplest solution (as for several others backward incompatibilities) for EPUB 3.2 would be to spend a new version number

and @clapierre 
> One idea may be that any EPUB's marked as version 3.2

The version number specified in the Package document MUST be "3.0", this was intentional in EPUB 3.2, and is a precondition of any intent to make EPUB 3.2 as backward compatible as possible with EPUB 3.0.1. See also w3c/publ-epub-revision#1009.

This implies that there is possibly no way to tell whether an EPUB is intended to conform to EPUB 3.0.1 or EPUB 3.2, and it's one of the primary reason why we decided to not differentiated EPUB 3.x versions in EPUBCheck (see  w3c/publ-cg#68).

That said, unfortunately EPUB 3.2 is not as backward compatible as one might hope; for instance due to elements/attributes removed in HTML. The additional issue is that distributors tend to treat WARNING as legit cause of rejection, so that implicitly makes any deprecated feature another _de facto_ source of backward incompatibility.

@ShinyaTakami 
> We appreciate that developers for epubcheck will recognize this WARNING issues as critical in Japan.

We do! 😊 However for an issue like this I believe the onus is not on EPUBCheck developers, but rather **on the CG** to reach a consensus.

> Reconsideration of deprecating "display-seq" in EPUB3.2

I for one think that this may well be the best approach here; feel free to contribute to the discussion over at w3c/publ-epub-revision#1242

**Comment by clapierre** [comment]
@rdeltour I assume it was discussed in the CG the idea of adding a new sub-version number metadata field that would be separate and only added to EPUBs that were intended to conform to the 3.2 specification? 

So that the overall version number could stay at 3.0 for backward compatibility but the additional subversion would be 3.2 so one could tell if this is a new EPUB vs. an older EPUB.  I realize there would be no way to enforce that but this could get around some of these warning issues on deprecated items in HTML etc.

**Comment by mattgarrish** [comment]
> I for one think that this may well be the best approach here

It's the most expedient, as we want to move people away from features that have no or little support and whose futures aren't encouraging.

At the same time, we weren't supposed to deprecate anything that was in wide use, even if there realistically is little implementation hope. The reason document order of elements was defined as setting precedence is because that's what reading systems are doing. I doubt that will change even if we leave it around, but nothing breaks whether it is present or not.

> So that the overall version number could stay at 3.0 for backward compatibility but the additional subversion would be 3.2 so one could tell if this is a new EPUB vs. an older EPUB.

I proposed something like this in 3.1, but it doesn't solve the problem that EPUB is constantly in flux because we adapt with the web. I know I'm becoming a broken record, but the only way to ever validate to what a vendor expects is to validate to the same old version of epubcheck that they are using.

**Comment by toshiakikoike** [comment]
Thank you for the discussion.
I appreciate w3c/publ-epub-revision#1242 as a solution

**Comment by rdeltour** [comment]
Done in #994, to be released in v4.2.0-RC.
