### ISSUE TITLE
no error or warning when epub:type "cover" is not on a body or section context

### ISSUE THREAD

**Issue by vincent-gros** [w3c/epubcheck#992]
_(This is also related to the mapping provided by Daisy/Ace between epub:type and ARIA roles)_

**What is OK:**
According to https://w3c.github.io/dpub-aria/#doc-cover, `role="doc-cover"` must be on `<img>`. Indeed, EPUBCheck 4.2 beta reports an error if for example this value is on `<section>` or `<body>`.

**What seems to be KO:**
According to https://idpf.github.io/epub-vocabs/structure/#cover, the HTML contexts for `epub:type="cover"` are body or section.
But if this value is on an `<img>` tag (to be validated by the mapping provided by ACE), EPUBCheck 4.2 beta does not report ERROR or WARNING.

What do you think @rdeltour? This could also be an ACE issue.

**Comment by rdeltour** [comment]
> According to https://w3c.github.io/dpub-aria/#doc-cover, `role="doc-cover"` must be on `<img>`.

In fact, it's a bit more complex: the [role `doc-cover`](https://www.w3.org/TR/dpub-aria-1.0/#doc-cover) is a subclass of the role `img`; as such, it is theoretically allowed wherever the `img` role is allowed. For HTML, the rules are defined in the [ARIA in HTML](https://www.w3.org/TR/html-aria/) specification.

That said, since accessibility support for DPUB roles is not ideal (some browsers/AT do not yet recognize them), it is still recommended to use them on the elements which natively have their superclass semantics. For the `doc-cover` role, it indeed means that it is recommended to be used only on `img` elements.

> EPUBCheck 4.2 beta reports an error if for example this value is on `<section>` or `<body>`.

As per ARIA in HTML, the `img`  role and its subclasses are not allowed to be set on `section` or `body` element, so EPUBCheck is correct in reporting that.

> According to https://idpf.github.io/epub-vocabs/structure/#cover, the HTML contexts for `epub:type="cover"` are body or section.

Right. And this is a source of confusion, especially since the [EPUB Structural Semantics to ARIA Roles Mapping Guide](EPUB Structural Semantics to ARIA Roles Mapping Guide) maps the `epub:type="cover" ` to the ARIA role `doc-cover`. 

Maybe the SSV could be updated to change the usage context of `cover`; or the mapping document should mention when the mapping isn't as straightforward as it seems. I'll let @mattgarrish comment on that one.

> if this value is on an `<img>` tag (to be validated by the mapping provided by ACE), EPUBCheck 4.2 beta does not report ERROR or WARNING.

Right, EPUBCheck does not check the HTML usage context defined in the SSV, since this context is only informative:

>>  Authors may use the properties on HTML markup elements not specifically listed

> This could also be an ACE issue.

Indeed; the confusion created by the SSV/DPUB-ARIA mapping is a known one, an I think Ace can do better in its report. The `cover` issue has been specifically reported in daisy/ace#201. See also daisy/ace#214.

**Comment by rdeltour** [comment]
> What do you think @rdeltour?

All in all, for the reasons explained in my previous comments, I think EPUBCheck is doing the right thing here.

I'll close this issue as `invalid`, but feel free to keep on discussing it in the comments, or reopen if you think EPUBCheck should do something else.

**Comment by Doktorchen** [comment]
https://www.w3.org/TR/wai-aria-1.1/#img 
describes about the superclass img:
'A container for a collection of elements that form an image.
An img can contain captions and descriptive text, as well as multiple image files that when viewed together give the impression of a single image.'

But img is an empty element, it cannot be a container for elements, cannot have a caption.
Container elements in HTML5, that can do this job are for example: figure, section, article, aside, div, but the content has to be only a collection representing one image, optionally with additional caption (figcaption for figure typically).
It can be a span containing multiple img elements, svg elements, object elements etc as well, if they represent only one image.

https://idpf.github.io/epub-vocabs/structure/#cover
is not necessarily related to an image at all. Lot of book covers have only text on it, no image at all. This seems to be only applicable, if no SVG or raster image is used as the cover, but an XHTML fragment.

**Comment by mattgarrish** [comment]
> Maybe the SSV could be updated to change the usage context of `cover`; or the mapping document should mention when the mapping isn't as straightforward as it seems. I'll let @mattgarrish comment on that one.

Yes, this one is actually more related to the cover-image property in the package document. The mapping document should be adjusted.

As I recall, we discussed the actual utility of the cover semantic in the SSV and found it didn't warrant a role (we were under heavy pressure to reduce the number of landmarks we were proposing), so we opted to make this the cover image designator.
